version: "3.4"
services:
  mongo:
    image: mongo:4.4.1
    volumes:
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=db_test
    ports:
      - "27017:27017"
    command: mongod --auth